name: Compile application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout working repository
      - name: Checkout working-directory
        uses: actions/checkout@v4

      # Install Arduino CLI on build agent      
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      # Install Arduino bard core libs
      - name: Install Board Core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      # Compile sketch code from all *.ino files
      - name: Compile all sketch files
        run: |
          mkdir -p ./all-hex-files

          # Loop through every .ino file in the examples folder
          find examples -name "*.ino" | while read -r sketch; do
            echo "Compiling $sketch..."
            
            # Extract filename
            name=$(basename "$sketch" .ino)
            
            # Compile to a temporary directory
            arduino-cli compile --fqbn arduino:avr:uno --output-dir "./temp_$name" "$sketch"
            
            # Move the generated hex file to our central artifact folder with a unique name
            mv "./temp_$name/${name}.ino.hex" "./all-hex-files/${name}.hex"
          done
          
      # Upload artifacts to Github
      - name: Upload all Hex Artifact
        uses: actions/upload-artifact@v4
        with:
          name: all-arduino-binaries
          path: ./all-hex-files/*.hex
          if-no-files-found: error
